[book]
authors = ["wuqi"]
language = "zh"
multilingual = true
src = "src"
title = "Map Projection"
[preprocessor.index]

[preprocessor.links]
[output.html]
mathjax-support = true

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
